# Generated by Django 5.0.7 on 2024-08-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_id',
            new_name='username',
        ),
    ]
