# Generated by Django 5.0.7 on 2024-08-04 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_password_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_confirm',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
