# Generated by Django 5.0.7 on 2024-08-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_password_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_introduce',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='blog_title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
