# Generated by Django 5.0.7 on 2024-07-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='content',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
