# Generated by Django 5.0.7 on 2024-07-30 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_user_board_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
