# Generated by Django 5.0.7 on 2024-07-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_board_modifydate_board_registdate_alter_board_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='modifyDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='registDate',
            field=models.DateTimeField(),
        ),
    ]
