# Generated by Django 5.0.7 on 2024-07-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_board_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='subTitle',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
