# Generated by Django 5.0.7 on 2024-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_board_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='modifyDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='registDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
