# Generated by Django 5.0.7 on 2024-08-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_alter_board_modifydate'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='등록자'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
