# Generated by Django 5.0.7 on 2024-08-04 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_alter_board_user_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
    ]
