# Generated by Django 5.0.7 on 2024-08-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_alter_board_content_alter_board_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='board/thumbnail'),
        ),
    ]
