# Generated by Django 5.0.7 on 2024-08-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_board_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='thumbnail_image',
            field=models.ImageField(upload_to='board/thumbnail'),
        ),
    ]
