# Generated by Django 5.0.7 on 2024-08-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_alter_board_thumbnail_image_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='upper_content_id',
        ),
        migrations.AlterField(
            model_name='board',
            name='subTitle',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
