# Generated by Django 5.0.7 on 2024-08-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_remove_comment_upper_content_id_alter_board_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upper_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.comment', verbose_name='답글'),
        ),
    ]
