# Generated by Django 5.0.7 on 2024-08-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_comment_upper_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='root_yn',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
