# Generated by Django 5.1 on 2024-08-15 07:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_comment_root_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=4000),
        ),
    ]
