# Generated by Django 5.1 on 2024-08-15 08:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_alter_board_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=4000),
        ),
    ]
